### ISSUE TITLE
Untranslatable app

### ISSUE THREAD

**Issue by pharaone** [Hankamotz/Fmessenger#1]
Please Add translation in this app. I Will translate it in italian

**Comment by Hankamotz** [comment]
Hi FaraoneLele! Thank for your suggestion. 
Fmessenger apps uses a link to the web version of messenger, as it is translated into many languages. You can try loging on Facebook and changing the language settings, then when you reopen Fmessenger should have changed the language.
![screenshot20160610_234511173](https://cloud.githubusercontent.com/assets/15349448/15979629/83a45bf0-2f65-11e6-8650-e701b51abfb0.png)

**Comment by pharaone** [comment]
Thanks!

**Comment by Hankamotz** [comment]
Hi FaraoneLele! I just updated Fmessenger and now is translatable: https://github.com/Hankamotz/Fmessenger/tree/Fmessenger_TRANSLATIONS
If yo want to translate to italian :)

**Comment by Hankamotz** [comment]
Good Work FaraoneLele, thanks!

**Comment by Hankamotz** [comment]
Hi! If you want you can also help translate the chess application
https://github.com/Hankamotz/xake-chess

**Comment by pharaone** [comment]
Done!

**Comment by pharaone** [comment]
;D

**Comment by Hankamotz** [comment]
Awesome! thanks again :)
