### ISSUE TITLE
Request: Please migrate to the OpenStore

### ISSUE THREAD

**Issue by zubozrout** [Hankamotz/Fmessenger#13]
Hello,
while I am sure the Canonical's announcement to abandon the development of Ubuntu touch stroke all of us hard I am happy to say that UBports has taken over and despite my initial fear that they won't be able to continue the work it is obvious now that the project is starting to take shape and some real work is being done over there.

Since there are many people on UBports images already + the team is working on a more smooth way to migrate Canonical-based images to UBports I would like to ask you to consider uploading your app to the OpenStore as well: https://open.uappexplorer.com/

This is a pretty simple and straight forward process and can be done with the existing click package.

Thank you very much.

**Comment by Hankamotz** [comment]
Thanks zubozrout, Fmessenger is already in openstore, I hope to fix the login issue soon. Thank you again.
