### ISSUE TITLE
Untranslatable app

### ISSUE THREAD

**Issue by ghost** [Hankamotz/Fmessenger#5]
Hello,
Could you please make this app translatable?
Thanks for this great work!

**Comment by Hankamotz** [comment]
Hi Anne017! Thank for your suggestion.
Fmessenger apps uses a link to the web version of messenger, as it is translated into many languages. You can try loging on Facebook and changing the language settings, then when you reopen Fmessenger should have changed the language.

**Comment by Hankamotz** [comment]
Hi Anne017! I just updated Fmessenger and now is translatable: https://github.com/Hankamotz/Fmessenger/tree/Fmessenger_TRANSLATIONS

**Comment by ghost** [comment]
Thanks you very much!
I have just made a pull request for the French translation.
Maybe this issue can be closed now?

**Comment by Hankamotz** [comment]
Ok, good work, thanks!
