### ISSUE TITLE
loading bar disappeared

### ISSUE THREAD

**Issue by merlijn-sebrechts** [Hankamotz/Fmessenger#8]
Latest update removed the loading bar on top of the application. Now I have no way of knowing if I tapped a button but the page is loading or if the "tap" didn't work.

**Comment by merlijn-sebrechts** [comment]
Just a note, this is the most important and pressing issue for me. I really thought stuff like photo upload was broken because I push the upload button and nothing happens...

**Comment by Hankamotz** [comment]
Hi galgalesh! The photo uploading worked again since 0.8.2 version when file picker was restored, please try updating app.
Coming days i will try to restore any kind of loading bar ;)

**Comment by Hankamotz** [comment]
Already I have restored loading bar and it works well, coming days a will update the app adding this feature,  thanks galgalesh for your sugestion ;)

**Comment by merlijn-sebrechts** [comment]
Awesome! Thanks!

Op zondag 15 januari 2017 heeft Hankamotz <notifications@github.com> het
volgende geschreven:
> Already I have restored loading bar and it works well, coming days a will
update the app adding this feature, thanks galgalesh for your sugestion ;)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/b8p1rIASsCWBNzpEzV3hQR7azqU_2RR-i-ckRXGEgcIcqBlYLZxvmCkr8EhkiQYmCbd54Yo0gkv6gubOa_jIO7cag_15m9GwqDc_gxvEPZrgGb8Co6pssxqGLehXY8ZTzYIFTFhKCLJKtHwtuU2z2dh4lWXgUA=s0-d-e1-ft#https://github.com/notifications/beacon/ABbH9fZRGWDQv-gz4gcMfcTRza9ZmbbUks5rSgTXgaJpZM4LF67v.gif>

**Comment by Hankamotz** [comment]
Done, loading bar added to last update (v.0.8.4)
